version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network
    command: >
      sh -c "aerich init-db && aerich migrate && aerich upgrade && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - TORTOISE_ORM=${TORTOISE_ORM}
      - PYTHONPATH=/app



  db:
    image: postgres:16-alpine
    restart: on-failure
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"


networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  app_data:
    driver: local
